apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
  labels:
    name: nginx
    purpose: taints-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx
      purpose: taints-demo
  template:
    metadata:
      labels:
        name: nginx
        purpose: taints-demo
    spec:
      containers:
      - name: nginx
        image: nginx
        