apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
  labels:
    purpose: deployment
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: deployment
      project: roboshop
  template:
    metadata:
      labels:
        purpose: deployment
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx