apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: roboshop
  labels:
    project: roboshop
    purpose: taint-node
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      purpose: taint-node
  template:
    metadata:
      labels:
        project: roboshop
        purpose: taint-node
    spec:
      containers:
      - name: nginx
        image: nginx