apiVersion: apps/v1
kind: Deployment
metadata:
  name: taints-tolerations
  namespace: roboshop
  labels:
    purpose: taints-tolerations
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      purpose: taints-tolerations
      project: roboshop
  template:
    metadata:
      labels:
        purpose: taints-tolerations
        project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx
      nodeSelector:
        kubernetes.io/hostname: ip-192-168-1-38.ec2.internal
      tolerations:
      - key: "course"
        operator: "Equal"
        value: "k8s"
        effect: "NoSchedule"