apiVersion: apps/v1
kind: Deployment
metadata:
  name: taint-tolerations-demo
  namespace: roboshop
  labels:
    project: roboshop
    purpose: taint-tolerations
spec:
  replicas: 1
  selector: 
    matchLabels:
      project: roboshop
      purpose: taint-tolerations
  template:
    metadata:
      labels:
        project: roboshop
        purpose: taint-tolerations
    spec:
      containers:
      - name: nginx
        image: nginx