apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: topology.kubernetes.io/zone
          #- key: disktype
            operator: In
            values: 
            - us-east-1b
            #- ssd 
          - key: disktype
          #- key: disktype
            operator: In
            values: 
            - ssd
            #- ssd      
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
